name: deploy-new-version
run-name: ${{ github.actor}}
on:
- push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Deploy to VPS
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: |
                        eval "$(ssh-agent -s)"
                        ssh-add ~/.ssh/github_deploy
                        cd apps/steam-friends-mono/
                        bash fetch-and-build.sh